spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ashishgituser/micro-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-location: "classpath:/config"
          #search-locations: "file:///C://configlocation//config"
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "SDWEEE23i3SDD33443RRERRER3434"
server:
  port: 8071
